# Generated by Django 3.2.7 on 2021-10-31 17:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('link_rp5', models.URLField()),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.person')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('wind_speed_average', models.DecimalField(decimal_places=1, max_digits=3)),
                ('wind_speed_max', models.DecimalField(decimal_places=1, max_digits=3)),
                ('wind_direction', models.IntegerField(choices=[(1, 'Север'), (2, 'Северо-Восток'), (3, 'Восток'), (4, 'Юго-Восток'), (5, 'Юг'), (6, 'Юго-Запад'), (7, 'Запад'), (8, 'Северо-Запад')])),
                ('precipitation', models.IntegerField(choices=[(None, 'Любые'), (1, 'Нет'), (2, 'Слабые'), (3, 'Сильные')])),
                ('forecast_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='spots.forecastday')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('directions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Север'), (2, 'Северо-Восток'), (3, 'Восток'), (4, 'Юго-Восток'), (5, 'Юг'), (6, 'Юго-Запад'), (7, 'Запад'), (8, 'Северо-Запад')]), size=None)),
                ('wind_speed_min', models.DecimalField(decimal_places=1, max_digits=3)),
                ('wind_speed_max', models.DecimalField(decimal_places=1, max_digits=3)),
                ('temperature_min', models.DecimalField(decimal_places=1, max_digits=3)),
                ('temperature_max', models.DecimalField(decimal_places=1, max_digits=3)),
                ('wind_direction', models.IntegerField(choices=[(1, 'Север'), (2, 'Северо-Восток'), (3, 'Восток'), (4, 'Юго-Восток'), (5, 'Юг'), (6, 'Юго-Запад'), (7, 'Запад'), (8, 'Северо-Запад')])),
                ('precipitation', models.IntegerField(choices=[(None, 'Любые'), (1, 'Нет'), (2, 'Слабые'), (3, 'Сильные')])),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.spot')),
            ],
        ),
    ]
