# Generated by Django 3.2.7 on 2021-11-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='directions',
            new_name='wind_directions',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='wind_direction',
        ),
        migrations.AlterField(
            model_name='spot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spots_images'),
        ),
    ]
