# Generated by Django 3.2.7 on 2021-11-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_auto_20211102_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='temperature_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='condition',
            name='temperature_min',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='condition',
            name='wind_speed_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='condition',
            name='wind_speed_min',
            field=models.IntegerField(),
        ),
    ]
