# Generated by Django 3.2.7 on 2021-11-13 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_auto_20211102_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='spot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='spots.spot'),
            preserve_default=False,
        ),
    ]
