# Generated by Django 3.2.7 on 2021-11-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_forecast_spot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='precipitation',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='precipitation',
        ),
        migrations.AlterField(
            model_name='forecast',
            name='temperature',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='wind_speed_average',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='wind_speed_max',
            field=models.IntegerField(),
        ),
    ]
