# Generated by Django 3.2.7 on 2021-11-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0005_auto_20211113_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastday',
            name='date',
            field=models.DateField(),
        ),
    ]
