# Generated by Django 3.2.7 on 2021-11-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0006_alter_forecastday_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='wind_speed_average',
            new_name='wind_speed_min',
        ),
    ]
