# Generated by Django 3.2.7 on 2021-11-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_person_telegram_id'),
        ('spots', '0007_rename_wind_speed_average_forecast_wind_speed_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.forecastday')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.person')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.spot')),
            ],
        ),
    ]
