# Generated by Django 3.2.7 on 2021-11-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0008_notificationfact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationFact',
        ),
    ]
