# Generated by Django 3.2.7 on 2021-11-27 21:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0009_delete_notificationfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='sequence_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='wind_directions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Штиль'), (1, 'Север'), (2, 'Северо-Восток'), (3, 'Восток'), (4, 'Юго-Восток'), (5, 'Юг'), (6, 'Юго-Запад'), (7, 'Запад'), (8, 'Северо-Запад')]), size=None),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='wind_direction',
            field=models.IntegerField(choices=[(0, 'Штиль'), (1, 'Север'), (2, 'Северо-Восток'), (3, 'Восток'), (4, 'Юго-Восток'), (5, 'Юг'), (6, 'Юго-Запад'), (7, 'Запад'), (8, 'Северо-Запад')]),
        ),
    ]
