# Generated by Django 3.2.7 on 2021-12-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0010_auto_20211127_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='is_active',
            field=models.BooleanField(verbose_name='Активно?'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='temperature_max',
            field=models.IntegerField(verbose_name='Максимальная температура'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='temperature_min',
            field=models.IntegerField(verbose_name='Минимальная температура'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='wind_speed_max',
            field=models.IntegerField(verbose_name='Максимальная скорость ветра (м/с)'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='wind_speed_min',
            field=models.IntegerField(verbose_name='Минимальная скорость ветра (м/с)'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spots_images', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='link_rp5',
            field=models.URLField(verbose_name='Ссылка на сайте RP5'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
