version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=332503
      - POSTGRES_DB=wind_bot
  redis:
    image: redis
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A windBot worker -l INFO
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
      - celery
  bot:
    build: .
    command: python start_polling.py
    env_file:
      - ./.env.prod
    depends_on:
      - web

volumes:
  postgres_data: