version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=332503
      - POSTGRES_DB=wind_bot
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build: .
    image: app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    volumes:
      - ./:/usr/src/app/
    ports:
      - "80:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db
  celery:
    image: app
    command: celery -A windBot worker -l INFO
    depends_on:
      - redis
      - web
  celery-beat:
    image: app
    command: celery -A windBot beat -l INFO
    depends_on:
      - redis
      - web
  bot:
    image: app
    command: python start_polling.py
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - celery

volumes:
  postgres_data: