name: Push-Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: WindBot Deploy
        uses: llownall/checkout-deploy@v0.1.0
        with:
          username: root
          server: windbot.ru
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_path: /home/windBot
